### ISSUE TITLE
Stepper - horizontal orientation

### ISSUE THREAD

**Issue by charmis** [sparkdesignsystem/Backlog#1042]
Currently Spark Stepper component supports only vertical orientation. It would be nice to have if it supports horizontal orientation.

Something similar to:
![image](https://user-images.githubusercontent.com/2847449/83161043-ec3b2a00-a0d5-11ea-894a-4008047aa627.png)

User Story:
As a Spark User I want Sparks Stepper Component to have a property to set its orientation to horizontal/vertical.

**Comment by ssabo1** [comment]
Hi @charmis thank you!!! I want to let you know I'm going to close this issue out because we do have a Horizontal Stepper prioritized in our Spark UX Backlog. Here is the UX Issue pending priority order: https://github.com/sparkdesignsystem/Backlog/issues/756 This will go through Strategy, Accessibility, Content and Design before being built by Spark Engineers.
